In [1]:
from scipy.spatial import procrustes

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
import matplotlib.cm as cm

In [5]:
import cv2

In [21]:
target_x_img=cv2.imread('/Users/livw/Desktop/BF2846_PD_S8_Immunostain_unfixed.tif',0)

In [22]:
input_Y_img = cv2.imread('/Users/livw/Desktop/BF2846_PD_S8_Autorad_unfixed.tif',0)

In [45]:
X_pts = np.array([[684,666],[1038,546],[1146,678],[2754,1764],[5112,396],[4674,2070],[4038,930],[3828,924],[546,3018]]).astype(np.int)

In [24]:
Y_pts = np.array([[220,920],[452,844],[596,592],[1396,1260],[1892,700],[2516,760],[2464,1280],[768,1160],[716,1076]]).astype(np.int)

In [53]:
M=Y_pts.dot(np.linalg.pinv(X_pts))

In [16]:
R = np.eye(3)
R[0:2,0:2] = Tform['rotation']
S = np.eye(3) * Tform['scale'] 
S[2,2] = 1
t = np.eye(3)
t[0:2,2] = Tform['translation']
M = np.dot(np.dot(R,S),t.T).T
tr_Y_img = cv2.warpAffine(input_Y_img,M[0:2,:],(400,400))

IndexError: invalid index to scalar variable.

In [17]:
Tform

0.012005879470412366

In [19]:
mtxb.size()

TypeError: 'int' object is not callable

In [20]:
mtxb

array([[-0.46353544, -0.21485975],
       [-0.0867061 , -0.26336231],
       [ 0.39283242, -0.14172459],
       [ 0.44580638,  0.28168684],
       [-0.28839727,  0.3382598 ]])

In [21]:
mtxa

array([[-0.48252152, -0.27443411],
       [-0.07916369, -0.26237108],
       [ 0.34756628, -0.09122673],
       [ 0.46819666,  0.25633956],
       [-0.25407774,  0.37169236]])

In [25]:
from scipy.ndimage import interpolation

In [27]:
img2=interpolation.affine_transform(target_x_img,mtxa[0:2],offset=0.0, output_shape=None, output=None, order=3, mode='constant',cval=0.0, prefilter=True)

In [28]:
img2.show()

AttributeError: 'numpy.ndarray' object has no attribute 'show'

In [29]:
target_x_img.show()

AttributeError: 'numpy.ndarray' object has no attribute 'show'

In [11]:
img3=interpolation.affine_transform(input_Y_img,mtxb[0:2],offset=0.0, output_shape=None, output=None, order=3, mode='constant',cval=0.0, prefilter=True)

NameError: name 'interpolation' is not defined

In [38]:
plt.imshow(img2)

In [43]:
plt.figure()

In [44]:
plt.show()

In [46]:
plt.imshow(img2)

img2

In [47]:
img2

array([[223,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ..., 
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [48]:
img3

array([[243,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       ..., 
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]], dtype=uint8)

In [54]:
M

array([[-0.01972072, -1.11353439,  0.83493034],
       [ 0.07839663,  0.64881859,  0.67406248],
       [ 0.06650796, -1.54628474,  2.78806447]])

In [55]:
target_x_img

array([[223, 224, 223, ..., 223, 223, 223],
       [223, 223, 223, ..., 223, 223, 223],
       [224, 223, 223, ..., 223, 223, 223],
       ..., 
       [223, 224, 223, ..., 222, 222, 223],
       [223, 223, 223, ..., 223, 223, 223],
       [223, 223, 224, ..., 223, 223, 222]], dtype=uint8)

In [57]:
input_Y_img

array([[243, 242, 241, ..., 243, 243, 244],
       [243, 242, 241, ..., 245, 245, 245],
       [241, 242, 242, ..., 247, 247, 247],
       ..., 
       [246, 246, 247, ..., 244, 244, 245],
       [241, 241, 243, ..., 244, 244, 245],
       [234, 233, 237, ..., 244, 244, 243]], dtype=uint8)

In [65]:
M2=cv2.getAffineTransform(Y_pts, X_pts)

In [66]:
M2

array([[  5.65766777e-01,  -1.69122486e-01,  -2.51960845e+01],
       [  8.18837417e-03,   4.56269787e-01,  -6.75113785e+01]])

In [37]:
rows, cols=target_x_img.shape

In [22]:
dst=cv2.warpAffine(input_Y_img, M2, (cols,rows))

NameError: name 'M2' is not defined

In [24]:
plt.subplot(121),plt.imshow(target_x_img),plt.title('Input'),plt.ylim(900,0),plt.xlim(0,1400)

(<matplotlib.axes._subplots.AxesSubplot at 0x10bd80ed0>,
 (900, 0),
 (0, 1400))

In [25]:
plt.subplot(122),plt.imshow(dst),plt.title('Output'),plt.ylim(900,0),plt.xlim(0,1400)

(<matplotlib.axes._subplots.AxesSubplot at 0x10bd80250>,
 (900, 0),
 (0, 1400))

In [98]:
axes=plt.gca()

In [106]:
axes.set_xlim([0,1400])

(0, 1400)

In [107]:
axes.set_ylim([900, 0])

(900, 0)

In [26]:
plt.show()

In [26]:
cv2.estimateRigidTransform(Y_pts, X_pts, 0)

error: /Users/jhelmus/anaconda/conda-bld/work/opencv-2.4.8/modules/video/src/lkpyramid.cpp:1798: error: (-210) Both input images must have either 8uC1 or 8uC3 type in function cvEstimateRigidTransform


In [154]:
shape = (1, 10, 2) # Needs to be a 3D array
source = np.random.randint(0, 100, shape).astype(np.int)

In [170]:
source

array([[[45, 41],
        [32, 43],
        [93,  7],
        [23, 84],
        [22, 56],
        [88, 80],
        [15, 56],
        [ 2, 42],
        [79, 48],
        [87, 58]]])

In [19]:
Y_pts

array([[ 291,  180],
       [1242,  198],
       [2385,  675],
       [   1,    0],
       [   2,    1]])

In [157]:
target = source + np.array([1, 0]).astype(np.int)

In [38]:
transformation = cv2.estimateRigidTransform(Y_pts_shape, X_pts_shape, False)

In [174]:
target.shape

(1, 10, 2)

In [20]:
X_pts.shape

(5, 2)

In [32]:
 X_pts_shape = X_pts[None, 0:]

In [33]:
X_pts_shape.shape

(1, 9, 2)

In [35]:
Y_pts_shape=Y_pts[None,0:]

In [36]:
Y_pts_shape.shape

(1, 9, 2)

In [199]:
X_pts_shape

array([[[ 109,   17],
        [ 644,   33],
        [1210,  260]]])

In [39]:
new4=cv2.warpAffine(input_Y_img,transformation,(cols,rows))

In [1]:
import scipy.misc

In [5]:
from PIL import Image

ImportError: dlopen(//anaconda/lib/python2.7/site-packages/PIL/_imaging.so, 2): Library not loaded: @loader_path/../../../libtiff.5.dylib
  Referenced from: //anaconda/lib/python2.7/site-packages/PIL/_imaging.so
  Reason: Incompatible library version: _imaging.so requires version 8.0.0 or later, but libtiff.5.dylib provides version 7.0.0

In [41]:
cv2.imwrite('/Users/livw/Desktop/2846S2Areg.tif', new4)

True

In [34]:
png

NameError: name 'png' is not defined

In [38]:
dst[:904,:1440].shape

(904, 1440)

In [ ]:
target_x_img.shape

In [8]:
target_x_img

array([[223, 224, 223, ..., 223, 223, 223],
       [223, 223, 223, ..., 223, 223, 223],
       [224, 223, 223, ..., 223, 223, 223],
       ..., 
       [223, 224, 223, ..., 222, 222, 223],
       [223, 223, 223, ..., 223, 223, 223],
       [223, 223, 224, ..., 223, 223, 222]], dtype=uint8)

In [43]:
target_x_img.shape

(9472, 15104)

In [44]:
input_Y_img.shape

(1952, 2785)

In [19]:
new2.shape

(9472, 15104)

In [23]:
plt.subplot(121),plt.imshow(target_x_img),plt.title('Input')

(<matplotlib.axes._subplots.AxesSubplot at 0x106462fd0>,
 <matplotlib.text.Text at 0x106503750>)

In [24]:
plt.subplot(122),plt.imshow(dst),plt.title('Output')

(<matplotlib.axes._subplots.AxesSubplot at 0x106462590>,
 <matplotlib.text.Text at 0x106572110>)

In [69]:
r = 900.0 / new2.shape[1]
dim = (900, int(new2.shape[0] * r))
 
# perform the actual resizing of the image and show it
resized1 = cv2.resize(new2, dim, interpolation = cv2.INTER_AREA)

In [70]:
resized2=cv2.resize(target_x_img, dim, interpolation=cv2.INTER_AREA)

In [27]:
resized1.shape

(564, 900)

In [28]:
resized2.shape

(564, 900)

In [48]:
Y_pts_2 = np.array([[207,73],[555,75],[828,275],[465,317],[446,282],[441,319],[200,428],[181,442],[178,389]]).astype(np.int)

In [47]:
x_pts_2 = np.array([[205,74],[555,76],[830,276],[467,319],[446,283],[440,321],[201,430],[182,439],[180,396]]).astype(np.int)

In [35]:
 Y_pts2_shape = Y_pts_2[None, :]

In [34]:
Y_pts_shape.shape

(1, 9, 2)

In [38]:
transformation2 = cv2.estimateRigidTransform(Y_pts2_shape, x_pts2_shape, False)

In [37]:
x_pts2_shape=x_pts_2[None, :]

In [41]:
resized3=cv2.warpAffine(resized1,transformation2,(900,564))

In [67]:
new2.shape

(9472, 15104)

In [68]:
target_x_img.shape

(9472, 15104)

In [24]:
5+4

9

In [25]:
X_pts = np.array([[1164,2310],[1644,2100],[1164 1770],[3168,2100],[2220,1908],[4668,1704],[4908,2334],[4554,1632],[1530,606],[2874,930],[4356,1374]]).astype(np.int)

SyntaxError: invalid syntax (<ipython-input-25-5777e6540cc8>, line 1)

In [40]:
Y_pts

array([[ 507, 1191],
       [ 762, 1074],
       [ 504,  888],
       [1584, 1107],
       [1092,  981],
       [2439,  879],
       [2562, 1230],
       [2370,  837],
       [ 714,  264],
       [1452,  444],
       [2262,  687]])

In [42]:
cmap = plt.get_cmap('jet')

rgba_img = cmap(new4)
rgb_img = np.delete(rgba_img, 3, 2)

In [43]:
rgb_img

array([[[ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        ..., 
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5]],

       [[ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        ..., 
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5]],

       [[ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        ..., 
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5]],

       ..., 
       [[ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        ..., 
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5]],

       [[ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        ..., 
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5]],

       [[ 0. ,  0. ,  0.5],
        [ 0. ,  0. ,  0.5],
        [ 0

In [44]:
cv2.imwrite('/Users/livw/Desktop/2846S2AregCol.tif', rgb_img)

True

In [ ]:
target_x